local items = {
	CloudShogun = {Name = "CloudShogun", ImageId = "rbxassetid://100589315034830"},
	NeonKappa77 = {Name = "NeonKappa77", ImageId = "rbxassetid://138398311054387"},
	NovaMikan   = {Name = "NovaMikan", ImageId = "rbxassetid://75645924421652"},
	PixelRonin  = {Name = "PixelRonin", ImageId = "rbxassetid://73470546288874"},
	RamenRiderZ = {Name = "RamenRiderZ", ImageId = "rbxassetid://124725948041658"},
	TofuNinjaX =  {Name = "TofuNinjaX", ImageId = "rbxassetid://130991539811518"},
	TurboTanuki = {Name = "TurboTanuki", ImageId = "rbxassetid://92467881616934"},
}
return items