local items = {
	CloudShogun = {Name = "CloudShogun", ImageId = "rbxassetid://124689687376954"},
	NeonKappa77 = {Name = "NeonKappa77", ImageId = "rbxassetid://98336945147801"},
	NovaMikan   = {Name = "NovaMikan", ImageId = "rbxassetid://123201471932680"},
	PixelRonin  = {Name = "PixelRonin", ImageId = "rbxassetid://95368897457862"},
	RamenRiderZ = {Name = "RamenRiderZ", ImageId = "rbxassetid://138089512804502"},
	TofuNinjaX =  {Name = "TofuNinjaX", ImageId = "rbxassetid://94799178134461"},
	TurboTanuki = {Name = "TurboTanuki", ImageId = "rbxassetid://89803342308007"},
}
return items