local module = {
	Azure                   = {Name = "Azure",                   GemPrice = 100,  PassId = 1793614883},
	Dragon_Fire_Sword       = {Name = "Dragon Fire Sword",       GemPrice = 100,  PassId = 1793614883},
	Magical_Wand_Of_Lime    = {Name = "Magical Wand Of Lime",    GemPrice = 100,  PassId = 1793614883},
	Magical_wand            = {Name = "Magical wand",            GemPrice = 100,  PassId = 1793614883},
	Minecraft_Diamond_Sword = {Name = "Minecraft Diamond Sword", GemPrice = 100,  PassId = 1793614883},
	OverseerSword           = {Name = "OverseerSword",           GemPrice = 100,  PassId = 1793614883},
	Rainbow_Star_Periastron = {Name = "Rainbow Star Periastron", GemPrice = 100,  PassId = 1793614883},
	Sword                   = {Name = "Sword",                   GemPrice = 100,  PassId = 1793614883},
	Water_sword             = {Name = "Water sword",             GemPrice = 100,  PassId = 1793614883},
}
return module
