local module = {
	Magical_Wand_Of_Lime    = {Name = "Magical Wand Of Lime",    GemPrice = 10,  PassId = 1793614883},
	Sword                   = {Name = "Sword",                   GemPrice = 50,  PassId = 1793312248},
	Minecraft_Diamond_Sword = {Name = "Minecraft Diamond Sword", GemPrice = 100,  PassId = 1796254619},
	Magical_wand            = {Name = "Magical wand",            GemPrice = 150,  PassId = 1797118622},
	Water_sword             = {Name = "Water sword",             GemPrice = 200,  PassId = 1794108448},
	OverseerSword           = {Name = "OverseerSword",           GemPrice = 300,  PassId = 1793990813},
	Azure                   = {Name = "Azure",                   GemPrice = 500,  PassId = 1797498593},
	Dragon_Fire_Sword       = {Name = "Dragon Fire Sword",       GemPrice = 1000,  PassId = 1796440698},
	Rainbow_Star_Periastron = {Name = "Rainbow Star Periastron", GemPrice = 2000,  PassId = 1797112599},
}
return module
